### ISSUE TITLE
Add API endpoint for number of files in project

### ISSUE THREAD

**Issue by cvanmeter-rl** [isaacwengler/augur#2]
This metric will return the total number of files in a repository. This is useful for understanding how large a project is, because generally with more files, a project is more complex.

**Comment by isaacwengler** [comment]
Under development. Working endpoint with dummy data:

<img width="947" alt="Screen Shot 2022-11-17 at 4 30 22 PM" src="https://user-images.githubusercontent.com/59943206/202573907-903611b6-dc73-4af0-82a4-2d02f046707b.png">

**Comment by claytonwiemann** [comment]
The the data will be gotten from repo_labor.
The repo name will be a string,
The files will an unsigned integer.

**Comment by isaacwengler** [comment]
Schema for endpoint response: 
```
schema:
            items:
              properties:
                repo_id:
                  description: 'Example: 25540'
                  type: integer
                repo_git:
                  description: 'Example: https://github.com/chaoss/augur'
                  type: string
                repo_name:
                  description: 'Example: augur'
                  type: string
                files:
                  description: 'Example: 207'
                  type: integer
            type: array
```
