### ISSUE TITLE
Add API endpoint for individual file complexity

### ISSUE THREAD

**Issue by cvanmeter-rl** [isaacwengler/augur#3]
This metric will return the total number of lines of code per file. This is useful for understanding the complexity, because larger files can be more difficult to read, thus more complex. This metric can be derived from total lines, comment/blank lines, and total files in a project.

**Comment by claytonwiemann** [comment]
The the data will be gotten from repo_labor.
The repo_name will be a string,
The file_complexity will be an unsigned integer.

**Comment by isaacwengler** [comment]
Schema for endpoint response:
```
schema:
            items:
              properties:
                repo_id:
                  description: 'Example: 25540'
                  type: integer
                repo_git:
                  description: 'Example: https://github.com/chaoss/augur'
                  type: string
                repo_name:
                  description: 'Example: augur'
                  type: string
                sum_code_complexity:
                  description: 'Example: 0'
                  type: integer
                average_code_complexity:
                  description: 'Example: 0'
                  type: integer
            type: array
```
