### ISSUE TITLE
Add API endpoint for blank lines in project

### ISSUE THREAD

**Issue by cvanmeter-rl** [isaacwengler/augur#4]
This metric will return the total number of blank lines in a repository. This is useful for deriving other code complexity metrics, such as “Project Individual File Complexity” and “Project Level Total Lines”.

**Comment by isaacwengler** [comment]
Under development. Endpoint working with dummy data:

<img width="981" alt="Screen Shot 2022-11-17 at 4 26 22 PM" src="https://user-images.githubusercontent.com/59943206/202573320-b61e2859-9a88-4e10-b668-d3ed40f72492.png">

**Comment by claytonwiemann** [comment]
The the data will be gotten from repo_labor.
The repo_name will be a string,
The blank_lines will be an unsigned integer.

**Comment by isaacwengler** [comment]
Schema for endpoint response:
```
schema:
            items:
              properties:
                repo_id:
                  description: 'Example: 25540'
                  type: integer
                repo_git:
                  description: 'Example: https://github.com/chaoss/augur'
                  type: string
                repo_name:
                  description: 'Example: augur'
                  type: string
                blank_lines:
                  description: 'Example: 274734'
                  type: integer
                avg_blank_lines:
                  description: 'Example: 923'
                  type: integer
            type: array
```
