### ISSUE TITLE
Add API endpoint for total lines in project

### ISSUE THREAD

**Issue by cvanmeter-rl** [isaacwengler/augur#6]
This metric will return the total number of lines of code in a repository. This is useful for understanding how large a project is, because generally with more lines of code, a project is more complex. This should not include comment lines or blank lines.

**Comment by isaacwengler** [comment]
Under development. Endpoint stub with dummy data:

<img width="944" alt="Screen Shot 2022-11-17 at 4 23 16 PM" src="https://user-images.githubusercontent.com/59943206/202572872-26b38b96-5566-466f-b2c5-e05f21514f86.png">

**Comment by claytonwiemann** [comment]
The the data will be gotten from repo_labor.
The repo name will be a string,
The lines will be an unsigned integer.

**Comment by isaacwengler** [comment]
Initial query to select the total_lines for each repo:

```
SELECT
	e.repo_id,
	augur_data.repo.repo_git,
	augur_data.repo.repo_name,
	e.total_lines
	FROM
	augur_data.repo,
	(SELECT 
			d.repo_id,
		    SUM(d.total_lines) AS total_lines
		FROM
			(SELECT
			        augur_data.repo_labor.repo_id,
				    augur_data.repo_labor.total_lines
			    FROM
			    	augur_data.repo_labor,
			        ( SELECT 
			        		augur_data.repo_labor.repo_id,
			        		MAX ( data_collection_date ) AS last_collected
			        	FROM 
			        		augur_data.repo_labor
			        	GROUP BY augur_data.repo_labor.repo_id) recent 
			    WHERE
			    	augur_data.repo_labor.repo_id = recent.repo_id
					AND augur_data.repo_labor.data_collection_date > recent.last_collected - (5 * interval '1 minute')) d
		GROUP BY d.repo_id) e
	WHERE augur_data.repo.repo_id = e.repo_id
```

**Comment by isaacwengler** [comment]
Schema for the response:
```
schema:
          items:
            properties:
              repo_id:
                description: 'Example: 25540'
                type: integer
              repo_git:
                description: 'Example: https://github.com/chaoss/augur'
                type: string
              repo_name:
                description: 'Example: augur'
                type: string
              total_lines:
                description: 'Example: 274734'
                type: integer
          type: array
```

An array of all repos, including the `total_lines` for each.
